version: "3.7"

services:
  app:
    build:
      context: .
      target: "${APP_ENV:-development}"
      args:
        APP_ENV: "${APP_ENV:-development}"
        MAIN_MODULE: "${MAIN_MODULE:-gapid}"
    volumes:
      - .:/app
    environment:
      APP_ENV: "${APP_ENV:-development}"
    ports:
      - "8000:8000"
