name: CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Run locally
        run: |
          DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 docker-compose up -d
          docker-compose exec -T app bash -c "while ! >/dev/tcp/localhost/8000; do sleep 3; done"
          curl -fisS http://localhost:8000/
